apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: test-newk8ssa-feb11-3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-newk8ssa-feb11-3
  name: test-newk8ssa-feb11-3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
